### ISSUE TITLE
Error while configuring module

### ISSUE THREAD

**Issue by zsavvas** [arietimmerman/OpenAM-U2F#1]
Hi, 

I tried to deploy the U2F authentication module but i get an error when adding the new authentication module. Specifically, i get a Resource 'IPlanetAmAuthU2FService' error as shown below
![opeam-u2f-error](https://cloud.githubusercontent.com/assets/4786593/13879801/01712eea-ed22-11e5-9eb2-5fbdc632aa0f.PNG)

The weird thing is that if i try to execute the first ssoadm command again i get a "Service already exists : iPlanetAMAuthU2FService , 1.0". It seems that the service is registered correctly but for a weird reason the module can't find it.

Any help is appreciated.
Thanks,
Savvas

**Comment by arietimmerman** [comment]
Thanks for reporting this issue!

It looks like you are trying to deploy this module in OpenAM 13, is that right?
Unfortunately, I haven't had the time to test the deployment for OpenAM 13. I can try to do this in the coming days. I'll keep you posted.

**Comment by zsavvas** [comment]
Hi,

Thanks for the rapid response. Actually, i am trying with the latest code and it is OpenAM 14.

**Comment by arietimmerman** [comment]
This evening I tried to reproduce your issues on an OpenAM 13 machine. I get the same error message.

It turned out it had something to to with the new configuration interface. I fixed some of the issues by adding a `resourceName`-attribute on `AttributeSchema`-elements in `src/main/resources/amAuthU2F.xml`. Now, it is possible to add this module for a chosen realm. However, it is still not possible to configure this module.

After some testing, I found that this is related to `AttributeSchema`-elements having `type="single_choice"`. If I remove all these elements and reinstall the module, I am able to configure it.

For now, I am not able to fix this. I'll try fixing it again in one of the coming days.

**Comment by arietimmerman** [comment]
Problem solved.
Now you should be able to both install this module for a chosen realm, plus you should be able to configure it.

Turned out a property was missing in the `u2f.properties` file. Apparently, OpenAM 12 didn't really care, while OpenAM >13 requires this property to be present.

Please confirm this fixes this issue you reported.

**Comment by zsavvas** [comment]
Dear Arie,

I can confirm that your changes fixes this issue in my configuration (OpenAM 14.0 Snapshot). Thanks a lot for your efforts!

Best regards,
Savvas
